import React from 'react';
import { RoadmapItem, Question, TopicCategory } from '../types';
import { Calendar, CheckCircle, Brain, Database, Code } from 'lucide-react';

interface PrintLayoutProps {
  roadmap: RoadmapItem[];
  sqlQuestions: Question[];
  dsaQuestions: Question[];
}

const PrintLayout: React.FC<PrintLayoutProps> = ({ roadmap, sqlQuestions, dsaQuestions }) => {
  return (
    <div className="hidden print-visible bg-white text-black p-8 max-w-4xl mx-auto">
      <div className="mb-8 border-b-2 border-black pb-4">
        <h1 className="text-4xl font-bold mb-2">Interview Sprint: 48h Prep Guide</h1>
        <p className="text-lg text-gray-600">Generated Roadmap & Question Bank for SQL + DSA</p>
        <p className="text-sm text-gray-500 mt-2">Date Generated: {new Date().toLocaleDateString()}</p>
      </div>

      {/* Roadmap Section */}
      <section className="mb-12 print-break-inside-avoid">
        <h2 className="text-2xl font-bold mb-6 flex items-center gap-2 border-b border-gray-300 pb-2">
          <Calendar className="w-6 h-6" /> 48-Hour Roadmap
        </h2>
        <div className="space-y-6">
          {[1, 2].map(day => {
            const dayItems = roadmap.filter(r => r.day === day);
            if (dayItems.length === 0) return null;
            return (
              <div key={day} className="mb-6">
                <h3 className="text-xl font-bold mb-4 uppercase tracking-wider bg-gray-100 p-2">Day {day}</h3>
                <div className="grid grid-cols-1 gap-4">
                  {dayItems.map((item, idx) => (
                    <div key={idx} className="flex gap-4 border-l-4 border-gray-800 pl-4 py-1">
                      <div className="w-32 flex-shrink-0 font-mono font-bold text-gray-700">{item.timeRange}</div>
                      <div>
                        <div className="font-bold text-lg">{item.activity}</div>
                        <div className="text-sm text-gray-600 italic mb-1">{item.focusArea}</div>
                        <div className="text-gray-800">{item.details}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* SQL Section */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6 flex items-center gap-2 border-b border-gray-300 pb-2 break-before-page">
          <Database className="w-6 h-6" /> SQL Question Bank ({sqlQuestions.length})
        </h2>
        <div className="space-y-6">
          {sqlQuestions.map((q, idx) => (
            <div key={q.id} className="mb-6 print-break-inside-avoid border border-gray-200 p-4 rounded-lg shadow-sm">
              <div className="flex justify-between items-start mb-2">
                <span className="font-mono text-xs font-bold bg-gray-100 px-2 py-1 rounded text-gray-600">Q{idx + 1} • {q.topic}</span>
                <span className="text-xs font-bold border border-gray-300 px-2 py-1 rounded">{q.difficulty}</span>
              </div>
              <h3 className="text-lg font-bold mb-3">{q.question}</h3>
              <div className="bg-gray-50 p-4 rounded text-sm font-mono whitespace-pre-wrap text-gray-800">
                {q.answer}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* DSA Section */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6 flex items-center gap-2 border-b border-gray-300 pb-2 break-before-page">
          <Code className="w-6 h-6" /> DSA Question Bank ({dsaQuestions.length})
        </h2>
        <div className="space-y-6">
          {dsaQuestions.map((q, idx) => (
            <div key={q.id} className="mb-6 print-break-inside-avoid border border-gray-200 p-4 rounded-lg shadow-sm">
              <div className="flex justify-between items-start mb-2">
                <span className="font-mono text-xs font-bold bg-gray-100 px-2 py-1 rounded text-gray-600">Q{idx + 1} • {q.topic}</span>
                <span className="text-xs font-bold border border-gray-300 px-2 py-1 rounded">{q.difficulty}</span>
              </div>
              <h3 className="text-lg font-bold mb-3">{q.question}</h3>
              <div className="bg-gray-50 p-4 rounded text-sm font-mono whitespace-pre-wrap text-gray-800">
                {q.answer}
              </div>
            </div>
          ))}
        </div>
      </section>

      <div className="text-center text-gray-400 text-sm mt-12 pb-12">
        End of Document • Generated by InterviewSprint AI
      </div>
    </div>
  );
};

export default PrintLayout;